services:

  db:
    image: postgres:latest
    container_name: postgres_db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes: 
      - db-volume:/var/lib/postgresql/pgdata
      
volumes:
  db-volume:
  