http_server:
  address: localhost:8080
  idle_timeout: 5s
db:
  dsn: "postgres://biba228:bibapassword228@localhost:5432/test?sslmode=disable"
song_details:
  url: "https://yourAddress/info"
log_level: debug
