// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Song struct {
	SongID      uuid.UUID   `json:"song_id"`
	Song        string      `json:"song"`
	Author      string      `json:"author"`
	ReleaseDate pgtype.Date `json:"release_date"`
	Text        string      `json:"text"`
	Link        string      `json:"link"`
}
